### ISSUE TITLE
Missing items on BOM

### ISSUE THREAD

**Issue by lildevilx** [eponra/flatpack#12]
Hello,

I was going through the BOM and cross referencing parts with the drawing and noticed that you have missed a leadscrew coupler for the Z axis. I'm assuming something like this? 
https://www.aliexpress.com/item/33031786581.html?spm=a2g0o.productlist.0.0.a48f22779ZPItU&algo_pvid=665d5f05-96fc-49e0-9bbf-61ddd560b318&algo_exp_id=665d5f05-96fc-49e0-9bbf-61ddd560b318-0&pdp_ext_f=%7B%22sku_id%22%3A%2267276553650%22%7D&pdp_npi=2%40dis%21CAD%216.37%214.14%21%21%21%21%21%402101e9ce16604001824212076e9adf%2167276553650%21sea&curPageLogUid=RP1jNQq7Xh6t
Also, is there any reason why you didn't opt for integrated lead screw motors? or is it just purely cost?

Since you're using the TMC2208 version of the AIO board, is there any reason why you didn't use sensorless homing?

Might be nice to add a flex plate bed into the BOM as well. 

I'm quite interested in building one of these and use when I'm traveling for work, hoping to see more improvements!

**Comment by eponra** [comment]
Hello there!

I missed the coupler, thanks for pointing that out. Will add that right away.
Also, its exactly the one from your link.

To the rest of your questions:
- integrated lead screw vs not integrated is not really a question of price. I like to be able to switch out motors, also i wanted a black leadscrew
- sensorless homing (so StallGuard) is not available on TMC2208 drivers
- i only add things to the BOM, which you really need for operation. Flexplate is an addon that will also cost some mm in Z

You can ofc add what you you want :)
