### ISSUE TITLE
24v part cooling

### ISSUE THREAD

**Issue by lildevilx** [eponra/flatpack#15]
FYI, the link for the part cooling fan brings you to the 12v version instead of the 24v. 
Feel free to ask me when I found out :P

**Comment by eponra** [comment]
Hey there!
I just followed that link out of the BOM, and asked others to follow the same link, and it definitely lead to the 24V version.
(its stated in the name, and in the picture it also shows 24V, and you cant choose anything else)

Either the link gets corrupted on aliexpress , and leads you to the wrong fan, or they sent you the wrong one?

**Comment by lildevilx** [comment]
Sorry, part hotend fan, not the part cooling.

- Exhaust Cooler Radiator Blower Fan

**Comment by eponra** [comment]
Ah! Checked it, and you´re right, that linked to a 12V version of the 3010 hotend fan you need.
Fixed it as of now!
Sorry for the inconvience!
