### ISSUE TITLE
ALIEXPRESS language urls

### ISSUE THREAD

**Issue by rredford** [eponra/flatpack#5]
Since your urls all start with DE, aliexpress will force everyone visiting site to have DE language. I suggest remove language part of url.

Example: https://www.aliexpress.com/item/2251832145008144.html?gatewayAdapt=glo2deu from https://de.aliexpress.com/item/2251832145008144.html?gatewayAdapt=glo2deu

**Comment by eponra** [comment]
Good point! I thought about changing that, but in the end forgot about it.

Thank you for pointing that out!

**Comment by rredford** [comment]
You're welcome!
