### ISSUE TITLE
Add missing parts to BOM

### ISSUE THREAD

**Issue by eponra** [eponra/flatpack#9]
The BOM is missing the belts (closed and open) and tnuts used.

**Comment by IDKhowtousethissiteLol** [comment]
Idlers, Pulleys, Endstops

**Comment by eponra** [comment]
Added missing parts to BOM, but still two parts missing. Will add them later, so i keep this issue open until resolved.

**Comment by eponra** [comment]
Added missing parts to BOM, slightly changed the setup for x and y-tensioner, am now re-uploading the fusion and step-files.
